%% Add personal paths
addpath('/Users/kdallo/Documents/EDHEC/Courses/Master Project/MATLAB Code/Other Functions')
addpath('/Users/kdallo/Documents/EDHEC/Courses/Master Project/MATLAB Code/Code')
addpath('/Users/kdallo/Documents/EDHEC/Courses/Master Project/MATLAB Code/Data')
addpath('/Users/kdallo/Documents/EDHEC/Courses/Master Project/MATLAB Code/Data/Dax - 2X')
addpath('/Users/kdallo/Documents/EDHEC/Courses/Master Project/MATLAB Code/Figures')

%% Some constants and variables
x = -2;         % Multiple (Leverage) = -2
figNb = 1;      % Counter 'i' for figures
nbBins = 100;   % Number of bins for distribution plots
lowerPerc = 10; % lower percentile
upperPerc = 90; % upper percentile

%% Read data from Excel file (has to be csv format)
% Weekly
[~, ~, rawDataD] = FNreadcsv('dailyPrices.csv');
datesRawD = rawDataD(2:end,1);
priceXSD2D = cell2mat(rawDataD(2:end,2));
priceDAXD = cell2mat(rawDataD(2:end,3));
returnXSD2D = priceXSD2D(2:end) ./ priceXSD2D(1:end-1) - 1;
returnDAXD = priceDAXD(2:end) ./ priceDAXD(1:end-1) - 1;
naiveReturnXSD2D = returnDAXD * x;
% Daily
[~, ~, rawDataW] = FNreadcsv('weeklyPrices.csv');
datesRawW = rawDataW(2:end,1);
priceXSD2W = cell2mat(rawDataW(2:end,2));
priceDAXW = cell2mat(rawDataW(2:end,3));
returnXSD2W = priceXSD2W(2:end) ./ priceXSD2W(1:end-1) - 1;
returnDAXW = priceDAXW(2:end) ./ priceDAXW(1:end-1) - 1;
naiveReturnXSD2W = returnDAXW * x;

%% Figure out historical periods with low, medium and high volatility
observationPeriod = zeros(252,1);
volPerPeriod = zeros(size(returnDAXD,1) - 252,1);
maxVol = 0; minVol = 1000; maxDate = 0; minDate = 0;
for i=1:size(returnDAXD,1) - 252
    observationPeriod = returnDAXD(i:i+252);
    volPerPeriod(i) = std(observationPeriod) * sqrt(252) * 100;
    if volPerPeriod(i) > maxVol
        maxVol = volPerPeriod(i);
        maxDate = datesRawD(i);
    end
    if volPerPeriod(i) < minVol
        minVol = volPerPeriod(i);
        minDate = datesRawD(i);
    end
end

figure(figNb)
figNb = figNb + 1;
plot(volPerPeriod);
grid on
title('Annualized DAX Volatility on a 252 Trading Days Rolling-Window')
xlabel('Number of the Rolling-Window')
ylabel('Annualized DAX Volatility')

%% Analyze these periods with DAILY returns
lowVol = 1650; medVol = 400; highVol = 310; annualizeFrequ = 252;
% Summary statistics for returns
% Low volatility
[ meanDAXLowD, medianDAXLowD, stdDAXLowD, minDAXLowD, maxDAXLowD, ...
    skewDAXLowD, kurtDAXLowD, excessKurtDAXLowD, nbPositivesDAXLowD, ...
    nbPercPosDAXLowD, tenPercDAXLowD, nintyPercDAXLowD, volDAXLowD] = ...
    distributionStatistics( returnDAXD(lowVol:lowVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanXSD2LowD, medianXSD2LowD, stdXSD2LowD, minXSD2LowD, maxXSD2LowD, ...
    skewXSD2LowD, kurtXSD2LowD, excessKurtXSD2LowD, nbPositivesXSD2LowD, ...
    nbPercPosXSD2LowD, tenPercXSD2LowD, nintyPercXSD2LowD, volXSD2LowD] ...
    = distributionStatistics( returnXSD2D(lowVol:lowVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanNaiveXSD2LowD, medianNaiveXSD2LowD, stdNaiveXSD2LowD, ...
    minNaiveXSD2LowD, maxNaiveXSD2LowD, skewNaiveXSD2LowD, ...
    kurtNaiveXSD2LowD, excessKurtNaiveXSD2LowD, nbPositivesNaiveXSD2LowD, ...
    nbPercPosNaiveXSD2LowD, tenPercNaiveXSD2LowD, nintyPercNaiveXSD2LowD, ...
    volNaiveXSD2LowD] = distributionStatistics( ...
    naiveReturnXSD2D(lowVol:lowVol+252), annualizeFrequ, ...
    lowerPerc, upperPerc );
% Return Deviation
[ meanRetDevLowD, medianRetDevLowD, stdRetDevLowD, ...
    minRetDevLowD, maxRetDevLowD, skewRetDevLowD, ...
    kurtRetDevLowD, excessKurtRetDevLowD, nbPositivesRetDevLowD, ...
    nbPercPosRetDevLowD, tenPercRetDevLowD, nintyPercRetDevLowD, ...
    volRetDevLowD] = distributionStatistics( ...
    returnXSD2D(lowVol:lowVol+252) - naiveReturnXSD2D(lowVol:lowVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
% Medium volatility
[ meanDAXMedD, medianDAXMedD, stdDAXMedD, minDAXMedD, maxDAXMedD, ...
    skewDAXMedD, kurtDAXMedD, excessKurtDAXMedD, nbPositivesDAXMedD, ...
    nbPercPosDAXMedD, tenPercDAXMedD, nintyPercDAXMedD, volDAXMedD ] = ...
    distributionStatistics( returnDAXD(medVol:medVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanXSD2MedD, medianXSD2MedD, stdXSD2MedD, minXSD2MedD, maxXSD2MedD, ...
    skewXSD2MedD, kurtXSD2MedD, excessKurtXSD2MedD, nbPositivesXSD2MedD, ...
    nbPercPosXSD2MedD, tenPercXSD2MedD, nintyPercXSD2MedD, volXSD2MedD ] = ...
    distributionStatistics( returnXSD2D(medVol:medVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanNaiveXSD2MedD, medianNaiveXSD2MedD, stdNaiveXSD2MedD, ...
    minNaiveXSD2MedD, maxNaiveXSD2MedD, skewNaiveXSD2MedD, ...
    kurtNaiveXSD2MedD, excessKurtNaiveXSD2MedD, nbPositivesNaiveXSD2MedD, ...
    nbPercPosNaiveXSD2MedD, tenPercNaiveXSD2MedD, nintyPercNaiveXSD2MedD, ...
    volNaiveXSD2MedD ] = distributionStatistics( ...
    naiveReturnXSD2D(medVol:medVol+252), annualizeFrequ, ...
    lowerPerc, upperPerc );
% Return Deviation
[ meanRetDevMedD, medianRetDevMedD, stdRetDevMedD, ...
    minRetDevMedD, maxRetDevMedD, skewRetDevMedD, ...
    kurtRetDevMedD, excessKurtRetDevMedD, nbPositivesRetDevMedD, ...
    nbPercPosRetDevMedD, tenPercRetDevMedD, nintyPercRetDevMedD, ...
    volRetDevMedD] = distributionStatistics( ...
    returnXSD2D(medVol:medVol+252) - naiveReturnXSD2D(medVol:medVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
% High volatility
[ meanDAXHighD, medianDAXHighD, stdDAXHighD, minDAXHighD, ...
    maxDAXHighD, skewDAXHighD, kurtDAXHighD, excessKurtDAXHighD, ...
    nbPositivesDAXHighD, nbPercPosDAXHighD, tenPercDAXHighD, ...
    nintyPercDAXHighD, volDAXHighD ] = distributionStatistics( ...
    returnDAXD(highVol:highVol+252), annualizeFrequ, ...
    lowerPerc, upperPerc );
[ meanXSD2HighD, medianXSD2HighD, stdXSD2HighD, minXSD2HighD, ...
    maxXSD2HighD, skewXSD2HighD, kurtXSD2HighD, excessKurtXSD2HighD, ...
    nbPositivesXSD2HighD, nbPercPosXSD2HighD, tenPercXSD2HighD, ...
    nintyPercXSD2HighD, volXSD2HighD ] = distributionStatistics( ...
    returnXSD2D(highVol:highVol+252), annualizeFrequ, ...
    lowerPerc, upperPerc );
[ meanNaiveXSD2HighD, medianNaiveXSD2HighD, stdNaiveXSD2HighD, ...
    minNaiveXSD2HighD, maxNaiveXSD2HighD, skewNaiveXSD2HighD, ...
    kurtNaiveXSD2HighD, excessKurtNaiveXSD2HighD, ...
    nbPositivesNaiveXSD2HighD, nbPercPosNaiveXSD2HighD, ...
    tenPercNaiveXSD2HighD, nintyPercNaiveXSD2HighD, volNaiveXSD2HighD ] = ...
    distributionStatistics( naiveReturnXSD2D(highVol:highVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );
% Return Deviation
[ meanRetDevHighD, medianRetDevHighD, stdRetDevHighD, ...
    minRetDevHighD, maxRetDevHighD, skewRetDevHighD, ...
    kurtRetDevHighD, excessKurtRetDevHighD, nbPositivesRetDevHighD, ...
    nbPercPosRetDevHighD, tenPercRetDevHighD, nintyPercRetDevHighD, ...
    volRetDevHighD] = distributionStatistics( ...
    returnXSD2D(highVol:highVol+252) - naiveReturnXSD2D(highVol:highVol+252), ...
    annualizeFrequ, lowerPerc, upperPerc );

%% Analyze these periods with WEEKLY returns
lowVol = 1650; medVol = 400; highVol = 310; annualizeFrequ = 52;
% Adjust DAX return vector of daily returns to 
% Summary statistics for returns
% Low volatility
[ meanDAXLowW, medianDAXLowW, stdDAXLowW, minDAXLowW, maxDAXLowW, ...
    skewDAXLowW, kurtDAXLowW, excessKurtDAXLowW, nbPositivesDAXLowW, ...
    nbPercPosDAXLowW, tenPercDAXLowW, nintyPercDAXLowW, volDAXLowW ] = ...
    distributionStatistics( returnDAXW(344:395), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanXSD2LowW, medianXSD2LowW, stdXSD2LowW, minXSD2LowW, maxXSD2LowW, ...
    skewXSD2LowW, kurtXSD2LowW, excessKurtXSD2LowW, nbPositivesXSD2LowW, ...
    nbPercPosXSD2LowW, tenPercXSD2LowW, nintyPercXSD2LowW, volXSD2LowW] ...
    = distributionStatistics( returnXSD2W(344:395), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanNaiveXSD2LowW, medianNaiveXSD2LowW, stdNaiveXSD2LowW, ...
    minNaiveXSD2LowW, maxNaiveXSD2LowW, skewNaiveXSD2LowW, ...
    kurtNaiveXSD2LowW, excessKurtNaiveXSD2LowW, nbPositivesNaiveXSD2LowW, ...
    nbPercPosNaiveXSD2LowW, tenPercNaiveXSD2LowW, nintyPercNaiveXSD2LowW, ...
    volNaiveXSD2LowW ] = distributionStatistics( naiveReturnXSD2W(344:395), ...
    annualizeFrequ, lowerPerc, upperPerc );
% Return Deviation low vol
[ meanRetDevLowW, medianRetDevLowW, stdRetDevLowW, ...
    minRetDevLowW, maxRetDevLowW, skewRetDevLowW, ...
    kurtRetDevLowW, excessKurtRetDevLowW, nbPositivesRetDevLowW, ...
    nbPercPosRetDevLowW, tenPercRetDevLowW, nintyPercRetDevLowW, ...
    volRetDevLowW ] = distributionStatistics( ...
    returnXSD2W(344:395) - naiveReturnXSD2W(344:395), ...
    annualizeFrequ, lowerPerc, upperPerc );
% Medium volatility
[ meanDAXMedW, medianDAXMedW, stdDAXMedW, minDAXMedW, maxDAXMedW, ...
    skewDAXMedW, kurtDAXMedW, excessKurtDAXMedW, nbPositivesDAXMedW, ...
    nbPercPosDAXMedW, tenPercDAXMedW, nintyPercDAXMedW, volDAXMedW ] = ...
    distributionStatistics( returnDAXW(83:134), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanXSD2MedW, medianXSD2MedW, stdXSD2MedW, minXSD2MedW, maxXSD2MedW, ...
    skewXSD2MedW, kurtXSD2MedW, excessKurtXSD2MedW, nbPositivesXSD2MedW, ...
    nbPercPosXSD2MedW, tenPercXSD2MedW, nintyPercXSD2MedW, volXSD2MedW ] = ...
    distributionStatistics( returnXSD2W(83:134), ...
    annualizeFrequ, lowerPerc, upperPerc );
[ meanNaiveXSD2MedW, medianNaiveXSD2MedW, stdNaiveXSD2MedW, ...
    minNaiveXSD2MedW, maxNaiveXSD2MedW, skewNaiveXSD2MedW, ...
    kurtNaiveXSD2MedW, excessKurtNaiveXSD2MedW, nbPositivesNaiveXSD2MedW, ...
    nbPercPosNaiveXSD2MedW, tenPercNaiveXSD2MedW, nintyPercNaiveXSD2MedW, ...
    volNaiveXSD2MedW ] = distributionStatistics( ...
    naiveReturnXSD2W(83:134), annualizeFrequ, ...
    lowerPerc, upperPerc );
% Return Deviation medium vol
[ meanRetDevMedW, medianRetDevMedW, stdRetDevMedW, ...
    minRetDevMedW, maxRetDevMedW, skewRetDevMedW, ...
    kurtRetDevMedW, excessKurtRetDevMedW, nbPositivesRetDevMedW, ...
    nbPercPosRetDevMedW, tenPercRetDevMedW, nintyPercRetDevMedW, ...
    volRetDevMedW ] = distributionStatistics( returnXSD2W(83:134) ...
    - naiveReturnXSD2W(83:134), annualizeFrequ, lowerPerc, upperPerc );
% High volatility
[ meanDAXHighW, medianDAXHighW, stdDAXHighW, minDAXHighW, ...
    maxDAXHighW, skewDAXHighW, kurtDAXHighW, excessKurtDAXHighW, ...
    nbPositivesDAXHighW, nbPercPosDAXHighW, tenPercDAXHighW, ...
    nintyPercDAXHighW, volDAXHighW ] = distributionStatistics( ...
    returnDAXW(65:116), annualizeFrequ, lowerPerc, upperPerc );
[ meanXSD2HighW, medianXSD2HighW, stdXSD2HighW, minXSD2HighW, ...
    maxXSD2HighW, skewXSD2HighW, kurtXSD2HighW, excessKurtXSD2HighW, ...
    nbPositivesXSD2HighW, nbPercPosXSD2HighW, tenPercXSD2HighW, ...
    nintyPercXSD2HighW, volXSD2HighW ] = distributionStatistics( ...
    returnXSD2W(65:116), annualizeFrequ, lowerPerc, upperPerc );
[ meanNaiveXSD2HighW, medianNaiveXSD2HighW, stdNaiveXSD2HighW, ...
    minNaiveXSD2HighW, maxNaiveXSD2HighW, skewNaiveXSD2HighW, ...
    kurtNaiveXSD2HighW, excessKurtNaiveXSD2HighW, ...
    nbPositivesNaiveXSD2HighW, nbPercPosNaiveXSD2HighW, ...
    tenPercNaiveXSD2HighW, nintyPercNaiveXSD2HighW, volNaiveXSD2HighW ] = ...
    distributionStatistics( naiveReturnXSD2W(65:116), ...
    annualizeFrequ, lowerPerc, upperPerc );
% Return Deviation high vol
[ meanRetDevHighW, medianRetDevHighW, stdRetDevHighW, ...
    minRetDevHighW, maxRetDevHighW, skewRetDevHighW, ...
    kurtRetDevHighW, excessKurtRetDevHighW, nbPositivesRetDevHighW, ...
    nbPercPosRetDevHighW, tenPercRetDevHighW, nintyPercRetDevHighW, ...
    volRetDevHighW ] = distributionStatistics( ...
    returnXSD2W(65:116) - naiveReturnXSD2W(65:116), ...
    annualizeFrequ, lowerPerc, upperPerc );

%% Plots (bar charts for daily and weekly comparing the three different
% conditions)

% Mean return deviation daily/weekly for low, med and high vol
meanRetDev = [ 0.008156687	-0.030198775	-0.045841612;
               0.048253228	-0.170999159	-0.296753955 ]';
category = categorical(["Low Vol" "Medium Vol" "High Vol"]);
category = reordercats(category,{'Low Vol' 'Medium Vol' 'High Vol'});
figure(figNb)
figNb = figNb + 1;
bar(category, meanRetDev);
grid on
title({'Mean Return Deviation for Daily & Weekly Holding Periods'})
legend({'Daily','Weekly'},'Location','southwest', 'FontSize', 14)
ylabel('%')
xlabel('Volatility')

% 10th percentile return deviation daily/weekly for low, med and high vol
meanRetDev = [ -0.6296071485	-0.7073852614	-0.7981365234
-1.2781790452	-1.7112578753	-1.9837936895 ]';
category = categorical(["Low Vol" "Medium Vol" "High Vol"]);
category = reordercats(category,{'Low Vol' 'Medium Vol' 'High Vol'});
figure(figNb)
figNb = figNb + 1;
bar(category, meanRetDev);
grid on
title({'10th Percentile Return Deviation for Daily & Weekly Holding Periods'})
legend({'Daily','Weekly'},'Location','southwest', 'FontSize', 14)
ylabel('%')
xlabel('Volatility')